
services:
  # SERVICIO 1: La Base de Datos
  postgres_db:
    image: postgres:15-alpine
    container_name: db_reservas
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: reservas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Aquí está la magia: esto evita que se borren los datos al apagar

  # SERVICIO 2: Tu código en FastAPI
  backend:
    build: 
      context: ./backend # Le dice que busque el Dockerfile dentro de la carpeta backend
    container_name: api_reservas
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:superpassword123@postgres_db:5432/reservas_db
    depends_on:
      - postgres_db # Obliga a que la base de datos inicie antes que el backend
      
 # SERVICIO 3: Frontend en React + Nginx
  frontend:
    build:
      context: ./frontend
    container_name: web_reservas
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

# Declaramos el volumen de persistencia
volumes:
  pgdata: